name: Running an action
on: 
  workflow_dispatch:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  speak:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
