name: 'Task 1: Running an action'
on: 
  workflow_dispatch:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
job:
  speak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, world!"