name: 'Task 1: Running an action'
on: 
  workflow_dispatch:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
job:
  speak:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - run: echo Hello World